name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  latest-release:
    name: "Tagged Release"
    runs-on: "ubuntu-18.04"

    steps:
      - uses: actions/checkout@v2
      - name: "Set up python3.9"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install dependencies"
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          poetry export -f requirements.txt --output requirements.txt
          pip install -r requirements.txt
      - name: "Build"
        run: |
          pip install pyinstaller
          pyinstaller -F -n vpnmd --hidden-import=libxtwrapper vpnmd/appd.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/vpnmd