name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-18.04"
    steps:
      - uses: actions/checkout@v2
      - name: "interpreter"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "requirements"
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          poetry export -f requirements.txt --output requirements.txt
          pip install -r requirements.txt
      - name: "linting"
        run: |
          pip install pylint
          pylint --max-line-length=88 --disable=C0114,C0116 --notes= ./vpnmd
      - name: "building"
        run: |
          pip install pyinstaller
          run pyinstaller -F -n vpnmd --clean --hidden-import=libxtwrapper vpnmd/appd.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/vpnmd
            